development:
  facebook:
    // TODO: set these values with variables
    client_id: "901417563579056"
    client_secret: "4ffa7ee827340fa070178a108951183a"
  google:
    client_id: GOOGLE_CLIENT_ID
    client_secret: GOOGLE_CLIENT_SECRET
    api_key: GOOGLE_API_KEY